-- CAISSEKOM SMARTPRICE ENTERPRISE — INSTALLATION CONSOLIDÉE
-- Base officielle Beta Complete
-- À exécuter dans Supabase SQL Editor sur un projet de test.
-- Les sections sont conservées dans leur ordre de migration historique.


-- ============================================================
-- SOURCE CONSOLIDÉE : INSTALLATION-SUPABASE-COMPLETE.sql
-- ============================================================

-- ============================================================
-- CAISSEKOM SMARTPRICE v1.9 QR DYNAMIC BETA 2.1 - CORRECTIF
-- INSTALLATION SUPABASE COMPLETE
--
-- MODE D'EMPLOI :
-- 1) Supabase > SQL Editor > New query
-- 2) Copier TOUT ce fichier
-- 3) Cliquer sur Run
--
-- Ce fichier est réexécutable. Il crée ou complète les tables
-- nécessaires sans supprimer le catalogue existant.
-- ============================================================

begin;

create extension if not exists pgcrypto;

-- ------------------------------------------------------------
-- 1. MAGASINS
-- ------------------------------------------------------------
create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  phone text,
  email text,
  website text,
  logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

insert into public.stores (id, name, updated_at)
values ('00000000-0000-0000-0000-000000000001', 'Magasin principal', now())
on conflict (id) do nothing;

-- ------------------------------------------------------------
-- 2. CATALOGUE HISTORIQUE
-- ------------------------------------------------------------
create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  barcode text not null unique,
  designation text not null,
  price numeric(14,2) not null default 0,
  category text,
  image text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 3. CATALOGUE MULTI-MAGASINS
-- ------------------------------------------------------------
create table if not exists public.store_products (
  store_id uuid not null references public.stores(id) on delete cascade,
  barcode text not null,
  designation text not null,
  price numeric(14,2) not null default 0,
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  primary key (store_id, barcode)
);

alter table public.store_products add column if not exists brand text;
alter table public.store_products add column if not exists category text;
alter table public.store_products add column if not exists manufacturer_ref text;
alter table public.store_products add column if not exists description text;
alter table public.store_products add column if not exists specifications text;
alter table public.store_products add column if not exists promo_price numeric(14,2);
alter table public.store_products add column if not exists promo_start timestamptz;
alter table public.store_products add column if not exists promo_end timestamptz;
alter table public.store_products add column if not exists featured boolean not null default false;
alter table public.store_products add column if not exists is_new boolean not null default false;
alter table public.store_products add column if not exists images jsonb not null default '[]'::jsonb;
alter table public.store_products add column if not exists related_codes jsonb not null default '[]'::jsonb;
alter table public.store_products add column if not exists availability text not null default 'available';

do $$
begin
  alter table public.store_products
    add constraint store_products_availability_check
    check (availability in ('available','out_of_stock','temporary','coming_soon'));
exception
  when duplicate_object then null;
end
$$;

insert into public.store_products
  (store_id, barcode, designation, price, active, updated_at)
select
  '00000000-0000-0000-0000-000000000001',
  p.barcode,
  p.designation,
  p.price,
  p.active,
  p.updated_at
from public.products p
on conflict (store_id, barcode) do nothing;

-- ------------------------------------------------------------
-- 4. JOURNAL DES IMPORTS
-- ------------------------------------------------------------
create table if not exists public.imports (
  id bigint generated by default as identity primary key,
  store_id uuid references public.stores(id) on delete set null,
  filename text,
  total_rows integer not null default 0,
  added_rows integer not null default 0,
  updated_rows integer not null default 0,
  error_rows integer not null default 0,
  deactivated_rows integer not null default 0,
  mode text not null default 'merge',
  created_at timestamptz not null default now()
);

alter table public.imports add column if not exists store_id uuid references public.stores(id) on delete set null;

-- ------------------------------------------------------------
-- 5. SMARTPRICE STUDIO
-- ------------------------------------------------------------
create table if not exists public.smartprice_settings (
  store_id uuid primary key references public.stores(id) on delete cascade,
  configuration jsonb not null default '{}'::jsonb,
  version text not null default '1.9-beta2.1',
  updated_at timestamptz not null default now()
);

alter table public.smartprice_settings
  add column if not exists version text not null default '1.9-beta2.1';
alter table public.smartprice_settings
  add column if not exists updated_at timestamptz not null default now();

-- ------------------------------------------------------------
-- 6. QR DYNAMIQUES
-- ------------------------------------------------------------
create table if not exists public.smartprice_access_tokens (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  token_hash text not null unique,
  label text,
  point_of_sale text,
  expires_at timestamptz not null,
  max_uses integer not null default 100 check (max_uses > 0),
  use_count integer not null default 0 check (use_count >= 0),
  session_minutes integer not null default 120 check (session_minutes between 1 and 1440),
  allow_reuse boolean not null default true,
  single_device boolean not null default false,
  bound_device_id text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  last_used_at timestamptz
);

alter table public.smartprice_access_tokens add column if not exists point_of_sale text;
alter table public.smartprice_access_tokens add column if not exists allow_reuse boolean not null default true;
alter table public.smartprice_access_tokens add column if not exists single_device boolean not null default false;
alter table public.smartprice_access_tokens add column if not exists bound_device_id text;

create table if not exists public.smartprice_access_logs (
  id bigint generated by default as identity primary key,
  token_id uuid references public.smartprice_access_tokens(id) on delete set null,
  store_id uuid not null references public.stores(id) on delete cascade,
  created_at timestamptz not null default now(),
  result text not null check (result in ('accepted','denied')),
  reason text,
  device_id text,
  user_agent text
);

-- ------------------------------------------------------------
-- 7. INDEX
-- ------------------------------------------------------------
create index if not exists idx_products_barcode on public.products(barcode);
create index if not exists idx_products_active on public.products(active);
create index if not exists store_products_store_active_idx on public.store_products(store_id, active);
create index if not exists store_products_designation_idx on public.store_products(store_id, designation);
create index if not exists store_products_brand_idx on public.store_products(store_id, brand);
create index if not exists store_products_category_idx on public.store_products(store_id, category);
create index if not exists store_products_featured_idx
  on public.store_products(store_id, featured) where featured = true;
create index if not exists smartprice_settings_updated_idx
  on public.smartprice_settings(updated_at desc);
create index if not exists smartprice_access_tokens_store_idx
  on public.smartprice_access_tokens(store_id, created_at desc);
create index if not exists smartprice_access_tokens_hash_idx
  on public.smartprice_access_tokens(token_hash);
create index if not exists smartprice_access_logs_store_date_idx
  on public.smartprice_access_logs(store_id, created_at desc);

-- ------------------------------------------------------------
-- 8. VALIDATION ATOMIQUE DU QR
-- ------------------------------------------------------------
create or replace function public.smartprice_validate_access_token_v2(
  p_token_hash text,
  p_store_id uuid default null,
  p_device_id text default null,
  p_user_agent text default null
)
returns table(
  valid boolean,
  message text,
  reason text,
  token_id uuid,
  store_id uuid,
  session_minutes integer,
  expires_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v public.smartprice_access_tokens%rowtype;
  deny_reason text;
begin
  select *
  into v
  from public.smartprice_access_tokens t
  where t.token_hash = p_token_hash
    and (p_store_id is null or t.store_id = p_store_id)
  for update;

  if not found then
    return query
      select false, 'QR Code inconnu', 'Jeton introuvable',
             null::uuid, null::uuid, null::integer, null::timestamptz;
    return;
  end if;

  if not v.active then
    deny_reason := 'QR désactivé';
  elsif v.expires_at <= now() then
    deny_reason := 'QR expiré';
  elsif v.use_count >= v.max_uses then
    deny_reason := 'Limite d’utilisations atteinte';
  elsif not v.allow_reuse and v.use_count > 0 then
    deny_reason := 'QR déjà utilisé';
  elsif v.single_device
        and v.bound_device_id is not null
        and coalesce(p_device_id, '') <> v.bound_device_id then
    deny_reason := 'QR verrouillé sur un autre appareil';
  end if;

  if deny_reason is not null then
    insert into public.smartprice_access_logs
      (token_id, store_id, result, reason, device_id, user_agent)
    values
      (v.id, v.store_id, 'denied', deny_reason, p_device_id, p_user_agent);

    return query
      select false, 'Accès refusé', deny_reason,
             v.id, v.store_id, v.session_minutes, v.expires_at;
    return;
  end if;

  update public.smartprice_access_tokens
  set
    use_count = use_count + 1,
    last_used_at = now(),
    bound_device_id = case
      when single_device and bound_device_id is null then p_device_id
      else bound_device_id
    end
  where id = v.id;

  insert into public.smartprice_access_logs
    (token_id, store_id, result, reason, device_id, user_agent)
  values
    (v.id, v.store_id, 'accepted', 'Accès autorisé', p_device_id, p_user_agent);

  return query
    select true, 'Accès autorisé', '',
           v.id, v.store_id, v.session_minutes, v.expires_at;
end;
$$;

create or replace function public.smartprice_access_dashboard(p_store_id uuid)
returns table(
  active_qr bigint,
  expired_qr bigint,
  scans_today bigint,
  denied_today bigint
)
language sql
security definer
set search_path = public
as $$
  select
    (
      select count(*)
      from public.smartprice_access_tokens
      where store_id = p_store_id
        and active
        and expires_at > now()
        and use_count < max_uses
    ),
    (
      select count(*)
      from public.smartprice_access_tokens
      where store_id = p_store_id
        and expires_at <= now()
    ),
    (
      select count(*)
      from public.smartprice_access_logs
      where store_id = p_store_id
        and created_at >= date_trunc('day', now())
    ),
    (
      select count(*)
      from public.smartprice_access_logs
      where store_id = p_store_id
        and result = 'denied'
        and created_at >= date_trunc('day', now())
    );
$$;

-- ------------------------------------------------------------
-- 9. RLS ET POLITIQUES DU PROTOTYPE
-- ------------------------------------------------------------
alter table public.stores enable row level security;
alter table public.products enable row level security;
alter table public.store_products enable row level security;
alter table public.imports enable row level security;
alter table public.smartprice_settings enable row level security;
alter table public.smartprice_access_tokens enable row level security;
alter table public.smartprice_access_logs enable row level security;

drop policy if exists "sp stores read" on public.stores;
drop policy if exists "sp stores write" on public.stores;
create policy "sp stores read" on public.stores
  for select to anon, authenticated using (true);
create policy "sp stores write" on public.stores
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "sp products read" on public.products;
drop policy if exists "sp products write" on public.products;
create policy "sp products read" on public.products
  for select to anon, authenticated using (active = true);
create policy "sp products write" on public.products
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "sp store_products read" on public.store_products;
drop policy if exists "sp store_products write" on public.store_products;
create policy "sp store_products read" on public.store_products
  for select to anon, authenticated using (true);
create policy "sp store_products write" on public.store_products
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "sp imports write" on public.imports;
create policy "sp imports write" on public.imports
  for insert to anon, authenticated with check (true);

drop policy if exists "sp settings read" on public.smartprice_settings;
drop policy if exists "sp settings write" on public.smartprice_settings;
create policy "sp settings read" on public.smartprice_settings
  for select to anon, authenticated using (true);
create policy "sp settings write" on public.smartprice_settings
  for all to anon, authenticated using (true) with check (true);

drop policy if exists "sp qr read" on public.smartprice_access_tokens;
drop policy if exists "sp qr create" on public.smartprice_access_tokens;
drop policy if exists "sp qr update" on public.smartprice_access_tokens;
create policy "sp qr read" on public.smartprice_access_tokens
  for select to anon, authenticated using (true);
create policy "sp qr create" on public.smartprice_access_tokens
  for insert to anon, authenticated with check (true);
create policy "sp qr update" on public.smartprice_access_tokens
  for update to anon, authenticated using (true) with check (true);

drop policy if exists "sp logs read" on public.smartprice_access_logs;
create policy "sp logs read" on public.smartprice_access_logs
  for select to anon, authenticated using (true);

-- ------------------------------------------------------------
-- 10. DROITS API
-- ------------------------------------------------------------
grant usage on schema public to anon, authenticated;
grant select, insert, update, delete on
  public.stores,
  public.products,
  public.store_products,
  public.smartprice_settings,
  public.smartprice_access_tokens
to anon, authenticated;

grant select, insert on public.imports to anon, authenticated;
grant select on public.smartprice_access_logs to anon, authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

revoke all on function public.smartprice_validate_access_token_v2(text, uuid, text, text) from public;
grant execute on function public.smartprice_validate_access_token_v2(text, uuid, text, text)
  to anon, authenticated;
grant execute on function public.smartprice_access_dashboard(uuid)
  to anon, authenticated;

commit;

-- Force le rechargement immédiat du schéma dans l'API Supabase.
notify pgrst, 'reload schema';


-- ============================================================
-- SOURCE CONSOLIDÉE : SMARTPRICE-V2-ALPHA1-SUPABASE.sql
-- ============================================================

-- SMARTPRICE v2.0 ENTERPRISE ALPHA 1
begin;
create extension if not exists pgcrypto;
create table if not exists public.smartprice_connectors (id uuid primary key default gen_random_uuid(),store_id uuid not null references public.stores(id) on delete cascade,connector_type text not null default 'caissekom',api_url text not null,api_key_encrypted text,frequency_minutes integer,enabled boolean not null default true,sync_fields jsonb not null default '["products","prices"]'::jsonb,last_test_at timestamptz,last_test_status text,last_sync_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(store_id,connector_type));
create table if not exists public.smartprice_sync_runs (id uuid primary key default gen_random_uuid(),connector_id uuid references public.smartprice_connectors(id) on delete set null,store_id uuid not null references public.stores(id) on delete cascade,status text not null check(status in ('running','success','partial','failed')),started_at timestamptz not null default now(),finished_at timestamptz,added_rows integer not null default 0,updated_rows integer not null default 0,error_rows integer not null default 0,message text,technical_details jsonb not null default '{}'::jsonb);
alter table public.smartprice_connectors enable row level security;alter table public.smartprice_sync_runs enable row level security;drop policy if exists "sp connectors alpha" on public.smartprice_connectors;create policy "sp connectors alpha" on public.smartprice_connectors for all to anon,authenticated using(true) with check(true);drop policy if exists "sp sync alpha" on public.smartprice_sync_runs;create policy "sp sync alpha" on public.smartprice_sync_runs for all to anon,authenticated using(true) with check(true);grant select,insert,update,delete on public.smartprice_connectors,public.smartprice_sync_runs to anon,authenticated;commit;notify pgrst,'reload schema';


-- ============================================================
-- SOURCE CONSOLIDÉE : SMARTPRICE-V2-BETA1-SUPABASE.sql
-- ============================================================

-- Caissekom SmartPrice v2.0 Enterprise Beta 1
-- À exécuter après SMARTPRICE-V2-ALPHA1-SUPABASE.sql
begin;
create extension if not exists pgcrypto;

create table if not exists public.smartprice_roles (
 id uuid primary key default gen_random_uuid(), code text unique not null, name text not null,
 permissions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
insert into public.smartprice_roles(code,name,permissions) values
 ('owner','Administrateur principal','{"all":true}'),
 ('store_admin','Administrateur magasin','{"stores":true,"catalog":true,"sync":true}'),
 ('department_manager','Responsable de rayon','{"catalog":true,"promotions":true}'),
 ('employee','Employé','{"catalog_read":true}') on conflict(code) do nothing;

create table if not exists public.smartprice_users (
 id uuid primary key default gen_random_uuid(), auth_user_id uuid, full_name text not null,
 email text not null, role_code text not null references public.smartprice_roles(code),
 store_id uuid references public.stores(id) on delete set null, active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table if not exists public.smartprice_product_variants (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade,
 sku text, barcode text, attributes jsonb not null default '{}'::jsonb, price numeric(14,2), active boolean not null default true,
 created_at timestamptz not null default now());

create table if not exists public.smartprice_promotions (
 id uuid primary key default gen_random_uuid(), store_id uuid references public.stores(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade, name text,
 promo_price numeric(14,2) not null, starts_at timestamptz not null, ends_at timestamptz,
 active boolean not null default true, created_at timestamptz not null default now());

create table if not exists public.smartprice_product_images (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade,
 image_url text not null, sort_order integer not null default 0, is_primary boolean not null default false,
 created_at timestamptz not null default now());

create table if not exists public.smartprice_price_history (
 id bigint generated by default as identity primary key, store_id uuid references public.stores(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade, old_price numeric(14,2), new_price numeric(14,2) not null,
 source text not null default 'manual', changed_at timestamptz not null default now(), changed_by text);

create table if not exists public.smartprice_monitor_events (
 id bigint generated by default as identity primary key, store_id uuid references public.stores(id) on delete cascade,
 severity text not null check(severity in ('info','warning','critical')), event_type text not null,
 message text not null, resolved_at timestamptz, details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now());

create index if not exists sp_variants_product_idx on public.smartprice_product_variants(product_id);
create index if not exists sp_promotions_active_idx on public.smartprice_promotions(store_id,starts_at,ends_at);
create index if not exists sp_price_history_idx on public.smartprice_price_history(product_id,changed_at desc);
create index if not exists sp_monitor_unresolved_idx on public.smartprice_monitor_events(store_id,created_at desc) where resolved_at is null;

alter table public.smartprice_roles enable row level security;
alter table public.smartprice_users enable row level security;
alter table public.smartprice_product_variants enable row level security;
alter table public.smartprice_promotions enable row level security;
alter table public.smartprice_product_images enable row level security;
alter table public.smartprice_price_history enable row level security;
alter table public.smartprice_monitor_events enable row level security;

-- Politiques Beta de démonstration. À durcir avant production avec auth.uid() et appartenance magasin.
do $$ declare t text; begin
 foreach t in array array['smartprice_roles','smartprice_users','smartprice_product_variants','smartprice_promotions','smartprice_product_images','smartprice_price_history','smartprice_monitor_events'] loop
  execute format('drop policy if exists %I on public.%I','beta authenticated access',t);
  execute format('create policy %I on public.%I for all to authenticated using (true) with check (true)','beta authenticated access',t);
 end loop;
end $$;

grant select,insert,update,delete on public.smartprice_roles,public.smartprice_users,public.smartprice_product_variants,public.smartprice_promotions,public.smartprice_product_images,public.smartprice_price_history,public.smartprice_monitor_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;
commit;
notify pgrst,'reload schema';
