-- Caissekom SmartPrice v2.0 Enterprise Beta 1
-- À exécuter après SMARTPRICE-V2-ALPHA1-SUPABASE.sql
begin;
create extension if not exists pgcrypto;

create table if not exists public.smartprice_roles (
 id uuid primary key default gen_random_uuid(), code text unique not null, name text not null,
 permissions jsonb not null default '{}'::jsonb, created_at timestamptz not null default now());
insert into public.smartprice_roles(code,name,permissions) values
 ('owner','Administrateur principal','{"all":true}'),
 ('store_admin','Administrateur magasin','{"stores":true,"catalog":true,"sync":true}'),
 ('department_manager','Responsable de rayon','{"catalog":true,"promotions":true}'),
 ('employee','Employé','{"catalog_read":true}') on conflict(code) do nothing;

create table if not exists public.smartprice_users (
 id uuid primary key default gen_random_uuid(), auth_user_id uuid, full_name text not null,
 email text not null, role_code text not null references public.smartprice_roles(code),
 store_id uuid references public.stores(id) on delete set null, active boolean not null default true,
 created_at timestamptz not null default now(), updated_at timestamptz not null default now());

create table if not exists public.smartprice_product_variants (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade,
 sku text, barcode text, attributes jsonb not null default '{}'::jsonb, price numeric(14,2), active boolean not null default true,
 created_at timestamptz not null default now());

create table if not exists public.smartprice_promotions (
 id uuid primary key default gen_random_uuid(), store_id uuid references public.stores(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade, name text,
 promo_price numeric(14,2) not null, starts_at timestamptz not null, ends_at timestamptz,
 active boolean not null default true, created_at timestamptz not null default now());

create table if not exists public.smartprice_product_images (
 id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade,
 image_url text not null, sort_order integer not null default 0, is_primary boolean not null default false,
 created_at timestamptz not null default now());

create table if not exists public.smartprice_price_history (
 id bigint generated by default as identity primary key, store_id uuid references public.stores(id) on delete cascade,
 product_id uuid not null references public.products(id) on delete cascade, old_price numeric(14,2), new_price numeric(14,2) not null,
 source text not null default 'manual', changed_at timestamptz not null default now(), changed_by text);

create table if not exists public.smartprice_monitor_events (
 id bigint generated by default as identity primary key, store_id uuid references public.stores(id) on delete cascade,
 severity text not null check(severity in ('info','warning','critical')), event_type text not null,
 message text not null, resolved_at timestamptz, details jsonb not null default '{}'::jsonb,
 created_at timestamptz not null default now());

create index if not exists sp_variants_product_idx on public.smartprice_product_variants(product_id);
create index if not exists sp_promotions_active_idx on public.smartprice_promotions(store_id,starts_at,ends_at);
create index if not exists sp_price_history_idx on public.smartprice_price_history(product_id,changed_at desc);
create index if not exists sp_monitor_unresolved_idx on public.smartprice_monitor_events(store_id,created_at desc) where resolved_at is null;

alter table public.smartprice_roles enable row level security;
alter table public.smartprice_users enable row level security;
alter table public.smartprice_product_variants enable row level security;
alter table public.smartprice_promotions enable row level security;
alter table public.smartprice_product_images enable row level security;
alter table public.smartprice_price_history enable row level security;
alter table public.smartprice_monitor_events enable row level security;

-- Politiques Beta de démonstration. À durcir avant production avec auth.uid() et appartenance magasin.
do $$ declare t text; begin
 foreach t in array array['smartprice_roles','smartprice_users','smartprice_product_variants','smartprice_promotions','smartprice_product_images','smartprice_price_history','smartprice_monitor_events'] loop
  execute format('drop policy if exists %I on public.%I','beta authenticated access',t);
  execute format('create policy %I on public.%I for all to authenticated using (true) with check (true)','beta authenticated access',t);
 end loop;
end $$;

grant select,insert,update,delete on public.smartprice_roles,public.smartprice_users,public.smartprice_product_variants,public.smartprice_promotions,public.smartprice_product_images,public.smartprice_price_history,public.smartprice_monitor_events to authenticated;
grant usage,select on all sequences in schema public to authenticated;
commit;
notify pgrst,'reload schema';
