-- Caissekom SmartPrice v1.6
-- Exécuter après les migrations précédentes.

alter table if exists public.store_products
  add column if not exists promo_price numeric(14,2),
  add column if not exists promo_start timestamptz,
  add column if not exists promo_end timestamptz,
  add column if not exists availability text not null default 'available';

do $$ begin
  alter table public.store_products add constraint store_products_availability_check
  check (availability in ('available','out_of_stock','temporary','coming_soon'));
exception when duplicate_object then null;
end $$;

create table if not exists public.sync_logs (
  id bigint generated by default as identity primary key,
  store_id uuid references public.stores(id) on delete cascade,
  source text not null default 'caissekom-api',
  status text not null default 'success',
  total_rows integer not null default 0,
  added_rows integer not null default 0,
  updated_rows integer not null default 0,
  deactivated_rows integer not null default 0,
  error_rows integer not null default 0,
  message text,
  created_at timestamptz not null default now()
);

alter table public.sync_logs enable row level security;
drop policy if exists "sync_logs_public_read" on public.sync_logs;
drop policy if exists "sync_logs_public_insert" on public.sync_logs;
create policy "sync_logs_public_read" on public.sync_logs for select using (true);
create policy "sync_logs_public_insert" on public.sync_logs for insert with check (true);

grant select, insert on public.sync_logs to anon, authenticated;
grant usage, select on sequence public.sync_logs_id_seq to anon, authenticated;

create index if not exists sync_logs_store_created_idx on public.sync_logs(store_id,created_at desc);
create index if not exists store_products_promo_idx on public.store_products(store_id,promo_start,promo_end);
