-- Caissekom SmartPrice v1.5 — Comptes, rôles et journal d’audit
-- Cette migration prépare la future authentification Supabase centralisée.
create table if not exists public.app_users (
  id uuid primary key default gen_random_uuid(),
  auth_user_id uuid unique,
  store_id uuid references public.stores(id) on delete set null,
  display_name text not null,
  username text unique,
  role text not null default 'employee' check (role in ('principal','manager','employee')),
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists app_users_store_idx on public.app_users(store_id);
create index if not exists app_users_role_idx on public.app_users(role);

create table if not exists public.audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references public.app_users(id) on delete set null,
  store_id uuid references public.stores(id) on delete set null,
  action text not null,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);
create index if not exists audit_logs_created_idx on public.audit_logs(created_at desc);
create index if not exists audit_logs_store_idx on public.audit_logs(store_id,created_at desc);

alter table public.app_users enable row level security;
alter table public.audit_logs enable row level security;
-- Les comptes de la v1.5 fonctionnent localement. Les politiques cloud sécurisées
-- seront activées lors du branchement à Supabase Auth dans une version ultérieure.
notify pgrst, 'reload schema';
