-- Caissekom SmartPrice v1.2 — catalogue central et journal des imports
create extension if not exists pgcrypto;

create table if not exists public.products (
  id uuid primary key default gen_random_uuid(),
  barcode text not null unique,
  designation text not null,
  price numeric(12,2) not null default 0,
  category text,
  image text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.stores (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  address text,
  phone text,
  email text,
  website text,
  logo text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.imports (
  id bigint generated by default as identity primary key,
  filename text,
  total_rows integer not null default 0,
  added_rows integer not null default 0,
  updated_rows integer not null default 0,
  error_rows integer not null default 0,
  deactivated_rows integer not null default 0,
  mode text not null default 'merge' check (mode in ('merge','replace')),
  created_at timestamptz not null default now()
);

create index if not exists idx_products_barcode on public.products(barcode);
create index if not exists idx_products_active on public.products(active);
create index if not exists idx_products_designation on public.products using gin (to_tsvector('simple', designation));

alter table public.products enable row level security;
alter table public.stores enable row level security;
alter table public.imports enable row level security;

drop policy if exists "smartprice products read" on public.products;
drop policy if exists "smartprice products write test" on public.products;
drop policy if exists "smartprice stores read" on public.stores;
drop policy if exists "smartprice stores write test" on public.stores;
drop policy if exists "smartprice imports write test" on public.imports;

create policy "smartprice products read" on public.products for select to anon using (active = true);
create policy "smartprice products write test" on public.products for all to anon using (true) with check (true);
create policy "smartprice stores read" on public.stores for select to anon using (true);
create policy "smartprice stores write test" on public.stores for all to anon using (true) with check (true);
create policy "smartprice imports write test" on public.imports for insert to anon with check (true);

grant usage on schema public to anon;
grant select, insert, update, delete on public.products to anon;
grant select, insert, update, delete on public.stores to anon;
grant insert on public.imports to anon;
grant usage, select on sequence public.imports_id_seq to anon;

insert into public.stores (id,name)
values ('00000000-0000-0000-0000-000000000001','CompuTime')
on conflict (id) do nothing;

notify pgrst, 'reload schema';
