import http from 'node:http';
import {createReadStream, existsSync, readFileSync, writeFileSync, mkdirSync, readdirSync} from 'node:fs';
import {extname, join, normalize, resolve} from 'node:path';
import {networkInterfaces} from 'node:os';

const root=resolve(process.cwd());
const dist=join(root,'dist');
const dataDir=join(root,'data');
const configFile=join(dataDir,'local-config.json');
const productFile=join(dataDir,'products.json');
const syncLogFile=join(dataDir,'sync-history.json');
const auditFile=join(dataDir,'audit-history.json');
const backupDir=join(dataDir,'backups');
mkdirSync(dataDir,{recursive:true});
mkdirSync(backupDir,{recursive:true});
const port=Number(process.env.SMARTPRICE_PORT||8080);
const mime={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.ico':'image/x-icon'};
const json=(res,status,payload)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':'*'});res.end(JSON.stringify(payload));};
const readJson=(file,fallback)=>{try{return JSON.parse(readFileSync(file,'utf8'))}catch{return fallback}};
const writeJson=(file,value)=>writeFileSync(file,JSON.stringify(value,null,2));
const readProducts=()=>readJson(productFile,[]);
const readConfig=()=>readJson(configFile,{storeName:'Mon magasin',address:'',phone:'',wifiSsid:'',wifiSecurity:'WPA',mode:'Local',setupComplete:false,port});
function audit(action,details={}){const items=readJson(auditFile,[]);items.unshift({id:Date.now(),date:new Date().toISOString(),action,details});writeJson(auditFile,items.slice(0,500));}
function safeName(value='backup'){return String(value).replace(/[^a-z0-9_.-]/gi,'-').replace(/-+/g,'-').slice(0,80)||'backup'}
function addresses(){const list=[];for(const [adapter,entries] of Object.entries(networkInterfaces()))for(const item of entries||[])if(item.family==='IPv4'&&!item.internal)list.push({adapter,name:item.address,url:`http://${item.address}:${port}`});return list;}
function body(req){return new Promise((ok,fail)=>{let raw='';req.on('data',c=>{raw+=c;if(raw.length>5_000_000){fail(new Error('Corps trop volumineux'));req.destroy();}});req.on('end',()=>{try{ok(raw?JSON.parse(raw):{})}catch(e){fail(e)}});req.on('error',fail)});}
function mapRows(rows=[]){const keys=Object.keys(rows[0]||{});const pick=(terms)=>keys.find(k=>terms.some(t=>k.toLowerCase().includes(t)))||'';const barcode=pick(['barcode','code barre','codebarre','ean','ref','code']);const designation=pick(['designation','désignation','libelle','libellé','produit','article']);const price=pick(['prix vente','prix','tarif','pv']);const stock=pick(['stock','qte','quantite','quantité']);const errors=[];const mapped=[];rows.forEach((r,i)=>{const code=String(r[barcode]||'').trim();const label=String(r[designation]||'').trim();const amount=Number(String(r[price]||'0').replace(',','.').replace(/[^0-9.-]/g,''));if(!code){errors.push({row:i+2,error:'Code-barres manquant'});return}if(!label){errors.push({row:i+2,error:'Désignation manquante'});return}mapped.push({id:Date.now()+i,barcode:code,designation:label,price:Number.isFinite(amount)?amount:0,stock:Number(String(r[stock]||'0').replace(/[^0-9.-]/g,''))||0,status:'Synchronisé',updatedAt:new Date().toISOString()});});return {mapped,errors,mapping:{barcode,designation,price,stock}};}

function createAutomaticBackup(reason='automatic'){
 const stamp=new Date().toISOString().replace(/[:.]/g,'-');
 const name=`${stamp}-${safeName(readConfig().storeName)}-${reason}.json`;
 const snapshot={version:'3.0 RC1',build:'008',date:new Date().toISOString(),reason,config:readConfig(),products:readProducts(),syncHistory:readJson(syncLogFile,[]),auditHistory:readJson(auditFile,[])};
 writeJson(join(backupDir,name),snapshot);audit('BACKUP_CREATED',{name,products:snapshot.products.length,reason});
 return name;
}
setInterval(()=>{try{createAutomaticBackup('daily')}catch(e){console.error('Sauvegarde automatique impossible',e)}},24*60*60*1000);

const server=http.createServer(async(req,res)=>{
 const url=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);
 if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':'*','Access-Control-Allow-Headers':'Content-Type','Access-Control-Allow-Methods':'GET,POST,PUT,DELETE,OPTIONS'});return res.end();}
 if(url.pathname==='/api/health')return json(res,200,{ok:true,service:'SmartPrice Local',version:'3.0 RC1',build:'008',time:new Date().toISOString(),uptimeSeconds:Math.round(process.uptime())});
 if(url.pathname==='/api/network')return json(res,200,{host:'smartprice.local',port,addresses:addresses()});
 if(url.pathname==='/api/setup-status'&&req.method==='GET')return json(res,200,{configured:Boolean(readConfig().setupComplete),config:readConfig()});
 if(url.pathname==='/api/local-config'&&req.method==='GET')return json(res,200,readConfig());
 if(url.pathname==='/api/local-config'&&req.method==='POST'){try{const next=await body(req);writeJson(configFile,{...readConfig(),...next,port});audit('CONFIG_UPDATED',{storeName:next.storeName||readConfig().storeName});return json(res,200,{ok:true,config:readConfig()})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(url.pathname==='/api/products'&&req.method==='GET'){const all=readProducts();const q=String(url.searchParams.get('q')||'').toLowerCase();const category=String(url.searchParams.get('category')||'');const sort=String(url.searchParams.get('sort')||'designation');const page=Math.max(1,Number(url.searchParams.get('page')||1));const pageSize=Math.min(200,Math.max(1,Number(url.searchParams.get('pageSize')||50)));let products=all.filter(p=>(!q||String(p.designation).toLowerCase().includes(q)||String(p.barcode).includes(q))&&(!category||String(p.category||'Non classé')===category));products.sort((a,b)=>sort==='price'?Number(a.price)-Number(b.price):sort==='stock'?Number(a.stock)-Number(b.stock):sort==='barcode'?String(a.barcode).localeCompare(String(b.barcode)):String(a.designation).localeCompare(String(b.designation),'fr'));return json(res,200,{products:products.slice((page-1)*pageSize,page*pageSize),total:products.length,page,pageSize,categories:[...new Set(all.map(p=>p.category||'Non classé'))].sort()});}
 if(url.pathname==='/api/products'&&req.method==='POST'){try{const p=await body(req);if(!p.barcode||!p.designation)return json(res,422,{ok:false,error:'Code-barres et désignation obligatoires'});const products=readProducts();if(products.some(x=>x.barcode===String(p.barcode)))return json(res,409,{ok:false,error:'Code-barres déjà existant'});const item={id:Date.now(),barcode:String(p.barcode).trim(),designation:String(p.designation).trim(),price:Number(p.price)||0,stock:Number(p.stock)||0,category:String(p.category||'Non classé'),family:String(p.family||''),status:'Créé',updatedAt:new Date().toISOString()};products.push(item);writeJson(productFile,products);audit('PRODUCT_CREATED',{id:item.id,barcode:item.barcode});return json(res,201,{ok:true,product:item})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 const productMatch=url.pathname.match(/^\/api\/products\/(\d+)$/);
 if(productMatch&&req.method==='PUT'){try{const id=Number(productMatch[1]);const patch=await body(req);const products=readProducts();const index=products.findIndex(p=>Number(p.id)===id);if(index<0)return json(res,404,{ok:false,error:'Article introuvable'});const barcode=String(patch.barcode??products[index].barcode).trim();if(products.some((p,i)=>i!==index&&p.barcode===barcode))return json(res,409,{ok:false,error:'Code-barres déjà existant'});products[index]={...products[index],...patch,id,barcode,status:'Modifié',updatedAt:new Date().toISOString()};writeJson(productFile,products);audit('PRODUCT_UPDATED',{id,barcode});return json(res,200,{ok:true,product:products[index]})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(productMatch&&req.method==='DELETE'){const id=Number(productMatch[1]);const products=readProducts();const found=products.find(p=>Number(p.id)===id);if(!found)return json(res,404,{ok:false,error:'Article introuvable'});writeJson(productFile,products.filter(p=>Number(p.id)!==id));audit('PRODUCT_DELETED',{id,barcode:found.barcode});return json(res,200,{ok:true});}
 if(url.pathname==='/api/products/bulk'&&req.method==='POST'){try{const payload=await body(req);const ids=new Set((payload.ids||[]).map(Number));if(!ids.size)return json(res,422,{ok:false,error:'Aucun article sélectionné'});let products=readProducts();const before=products.length;if(payload.action==='delete')products=products.filter(p=>!ids.has(Number(p.id)));else if(payload.action==='category')products=products.map(p=>ids.has(Number(p.id))?{...p,category:String(payload.category||'Non classé'),status:'Modifié',updatedAt:new Date().toISOString()}:p);else return json(res,422,{ok:false,error:'Action groupée inconnue'});writeJson(productFile,products);audit('PRODUCT_BULK_ACTION',{action:payload.action,requested:ids.size,affected:before-products.length||ids.size});return json(res,200,{ok:true,total:products.length})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(url.pathname==='/api/public/lookup'&&req.method==='GET'){const barcode=String(url.searchParams.get('barcode')||'').trim();const item=readProducts().find(p=>String(p.barcode)===barcode);if(!item)return json(res,404,{ok:false,error:'Article introuvable'});return json(res,200,{ok:true,product:{designation:item.designation,barcode:item.barcode,price:item.price,status:item.status,category:item.category||null}});}
 if(url.pathname==='/api/import'&&req.method==='POST'){try{const payload=await body(req);const {mapped,errors,mapping}=mapRows(payload.rows||[]);const current=readProducts();let created=0,updated=0;for(const item of mapped){const i=current.findIndex(p=>p.barcode===item.barcode);if(i>=0){current[i]={...current[i],...item,id:current[i].id};updated++}else{current.push(item);created++}}writeJson(productFile,current);const history=readJson(syncLogFile,[]);const entry={id:Date.now(),date:new Date().toISOString(),file:payload.fileName||'Import API',created,updated,rejected:errors.length,total:current.length,mapping};history.unshift(entry);writeJson(syncLogFile,history.slice(0,200));audit('IMPORT_COMPLETED',entry);return json(res,200,{ok:true,created,updated,rejected:errors.length,total:current.length,errors:errors.slice(0,100),mapping})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(url.pathname==='/api/sync-history'&&req.method==='GET')return json(res,200,{history:readJson(syncLogFile,[])});
 if(url.pathname==='/api/audit'&&req.method==='GET')return json(res,200,{history:readJson(auditFile,[])});
 if(url.pathname==='/api/diagnostics'&&req.method==='GET'){const products=readProducts();const config=readConfig();return json(res,200,{ok:true,checks:{dataDirectory:existsSync(dataDir),distDirectory:existsSync(dist),configuration:Boolean(config.storeName),networkAddresses:addresses().length,productDatabase:Array.isArray(products)},summary:{products:products.length,port,uptimeSeconds:Math.round(process.uptime()),memoryMb:Math.round(process.memoryUsage().rss/1024/1024)}});}
 if(url.pathname==='/api/backups'&&req.method==='GET'){const backups=readdirSync(backupDir).filter(x=>x.endsWith('.json')).sort().reverse().map(name=>({name}));return json(res,200,{backups});}
 if(url.pathname==='/api/backups'&&req.method==='POST'){try{const payload=await body(req);const stamp=new Date().toISOString().replace(/[:.]/g,'-');const name=`${stamp}-${safeName(payload.name||readConfig().storeName)}.json`;const snapshot={version:'3.0 RC1',build:'008',date:new Date().toISOString(),config:readConfig(),products:readProducts(),syncHistory:readJson(syncLogFile,[]),auditHistory:readJson(auditFile,[])};writeJson(join(backupDir,name),snapshot);audit('BACKUP_CREATED',{name,products:snapshot.products.length});return json(res,201,{ok:true,name,products:snapshot.products.length})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(url.pathname==='/api/backups/restore'&&req.method==='POST'){try{const payload=await body(req);const file=join(backupDir,safeName(payload.name));if(!existsSync(file))return json(res,404,{ok:false,error:'Sauvegarde introuvable'});const snapshot=readJson(file,null);if(!snapshot||!Array.isArray(snapshot.products))return json(res,422,{ok:false,error:'Sauvegarde invalide'});writeJson(productFile,snapshot.products);if(snapshot.config)writeJson(configFile,{...snapshot.config,port});audit('BACKUP_RESTORED',{name:payload.name,products:snapshot.products.length});return json(res,200,{ok:true,products:snapshot.products.length})}catch(e){return json(res,400,{ok:false,error:String(e)})}}
 if(url.pathname==='/api/stats'&&req.method==='GET'){const products=readProducts(),history=readJson(syncLogFile,[]);const today=new Date().toISOString().slice(0,10);const importedToday=history.filter(x=>String(x.date||'').slice(0,10)===today).reduce((n,x)=>n+(x.created||0)+(x.updated||0),0);return json(res,200,{products:products.length,stock:products.reduce((n,p)=>n+(Number(p.stock)||0),0),importedToday,lastSync:history[0]?.date||null,server:{port,addresses:addresses().length}});}
 if(!existsSync(dist))return json(res,503,{ok:false,error:'Le dossier dist est absent. Exécutez npm run build avant npm run local.'});
 let pathname=decodeURIComponent(url.pathname);if(pathname==='/'||!extname(pathname))pathname='/index.html';const file=normalize(join(dist,pathname));if(!file.startsWith(dist))return json(res,403,{error:'Accès refusé'});const target=existsSync(file)?file:join(dist,'index.html');res.writeHead(200,{'Content-Type':mime[extname(target)]||'application/octet-stream','Cache-Control':extname(target)==='.html'?'no-store':'public, max-age=3600'});createReadStream(target).pipe(res);
});
server.listen(port,'0.0.0.0',()=>{console.log(`SmartPrice Local Build 008 actif sur http://localhost:${port}`);for(const a of addresses())console.log(`Réseau magasin: ${a.url}`)});
